services:
  postgres:
    image: postgres:15-alpine
    container_name: solidjs-rust-postgres-dev
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-solidjs_rust_dev}
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-postgres}"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: solidjs-rust-redis-dev
    ports:
      - "6379:6379"
    volumes:
      - redis_data_dev:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ../backend
      dockerfile: Dockerfile
      target: development
    container_name: solidjs-rust-backend-dev
    environment:
      - DATABASE_URL=postgresql://${POSTGRES_USER:-postgres}:${POSTGRES_PASSWORD:-password}@postgres:5432/${POSTGRES_DB:-solidjs_rust_dev}
      - REDIS_URL=redis://redis:6379
      - RUST_LOG=debug
      - CORS_ORIGINS=http://localhost:8080
    ports:
      - "3000:3000"
    volumes:
      - ../backend:/app
      - backend_target_dev:/app/target
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    command: cargo watch -x run
    restart: unless-stopped

  frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile
      target: development
    container_name: solidjs-rust-frontend-dev
    environment:
      - NODE_ENV=development
      - VITE_API_BASE_URL=http://localhost:3000
    ports:
      - "8080:8080"
    volumes:
      - ../frontend:/app
      - frontend_node_modules_dev:/app/node_modules
    depends_on:
      - backend
    command: npm run dev
    restart: unless-stopped

volumes:
  postgres_data_dev:
  redis_data_dev:
  backend_target_dev:
  frontend_node_modules_dev:

networks:
  default:
    name: solidjs-rust-dev 